# Generated by Django 3.2.14 on 2022-08-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='sdfssg', upload_to='gallary'),
            preserve_default=False,
        ),
    ]
